#!/bin/sh
# <!-- **************************************  -->
# <!-- Don't Remove this Disclaimer            -->
# <!-- **************************************  -->
echo
echo "*****************************************"
echo "*         Uninstall freearhey           *"
echo "*****************************************"

if [ -d /usr/lib/python2.6 ]; then
if [ ! -d /usr/lib/python2.7 ]; then
echo "**********************************************************"
echo "*                        Oooooooops                      *"
echo "*                Not Compatible with (OE1.6)             *"
echo "**********************************************************"
sleep 2
exit 1 
fi
fi

EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/freearhey"

if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi

echo "*****************************************"
echo "*          ....done                     *"
echo "*****************************************"
exit 0


