#!/bin/sh

EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/freearhey"

if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi


echo "***********************************"
echo "* Proceeding to installation...   *"
echo "***********************************"
cd /
exit 0
